// Dev-only mock data — not included in production builds
export const mockAccounts = [
  {
    id: 'acc-001',
    name: 'Bloom Skincare',
    type: 'Client',
    assigned_to: 'Kiran',
    platforms: 'Instagram, Meta Ads',
    retainer_scope: '8 Instagram feed posts/month, 4 Reels, Meta Ads management (€1,500/mo ad spend)',
    ig_handle: 'bloomskincare',
    login_user: 'social@bloomskincare.ie',
    login_pass: 'Bloom2024!',
    notes: 'Focus on UGC-style content. Avoid overly polished aesthetics — brand voice is warm and approachable.',
    content_calendar_url: 'https://calendar.google.com/calendar/r',
    created_at: '2024-01-15',
    updated_at: '2024-04-10',
  },
  {
    id: 'acc-002',
    name: 'Volta Coffee',
    type: 'Client',
    assigned_to: 'Rebeka',
    platforms: 'Instagram, TikTok, Facebook',
    retainer_scope: '12 posts/month across IG + TikTok, monthly strategy call, paid social management',
    ig_handle: 'voltacoffee',
    login_user: 'hello@voltacoffee.com',
    login_pass: 'Volta#99',
    notes: 'Strong local Dublin audience. Best performing content: behind-the-scenes barista videos.',
    content_calendar_url: '',
    created_at: '2024-02-01',
    updated_at: '2024-04-12',
  },
  {
    id: 'acc-003',
    name: '@niamh.creates',
    type: 'Personal Brand',
    assigned_to: 'Kiran',
    platforms: 'Instagram, YouTube, LinkedIn',
    retainer_scope: 'Full content strategy + 10 IG posts/month + 2 YouTube scripts',
    ig_handle: 'niamh.creates',
    login_user: 'niamh@niamhcreates.com',
    login_pass: 'Niamh2024',
    notes: 'Interior design creator. Audience: 25–40F. Sponsors: IKEA, Dunnes Home. Avoid fast fashion brand deals.',
    content_calendar_url: '',
    created_at: '2024-03-10',
    updated_at: '2024-04-08',
  },
  {
    id: 'acc-004',
    name: 'Peak Performance Gym',
    type: 'Client',
    assigned_to: 'Rebeka',
    platforms: 'Instagram, Meta Ads, TikTok',
    retainer_scope: 'Lead gen Meta Ads, 6 IG posts/month, monthly analytics report',
    ig_handle: 'peakperformancegym',
    login_user: 'marketing@peakgym.ie',
    login_pass: 'Peak@Gym1',
    notes: 'January campaign drove 120 new members. Summer campaign brief due end of May.',
    content_calendar_url: '',
    created_at: '2024-01-20',
    updated_at: '2024-04-01',
  },
  {
    id: 'acc-005',
    name: '@marcoruns',
    type: 'Personal Brand',
    assigned_to: 'Rebeka',
    platforms: 'Instagram, TikTok',
    retainer_scope: '8 posts/month, Reels editing, brand deal negotiation support',
    ig_handle: 'marcoruns',
    login_user: 'marco@marcoruns.com',
    login_pass: 'Marco!Run24',
    notes: 'Running creator, 42k IG followers. Upcoming marathon partnership with Asics pending approval.',
    content_calendar_url: '',
    created_at: '2024-02-14',
    updated_at: '2024-03-28',
  },
]

export const mockContent = [
  { id: 'cnt-001', account_id: 'acc-001', week: '1', day: 'Monday', platform: 'Instagram', entry_type: 'Post', content_pillar: 'Product Promotion', visual_direction: 'SPF 50+ flat lay on marble', creative_url: '', caption_en: 'Summer skin sorted. Our SPF 50+ tinted moisturiser is here.', caption_hr: '', hashtags: '#skincare #spf #bloomskincare', status: 'In Review', notes: '', updated_at: '2024-04-10' },
  { id: 'cnt-002', account_id: 'acc-001', week: '1', day: 'Thursday', platform: 'Instagram', entry_type: 'Story', content_pillar: 'Lifestyle', visual_direction: 'Before/after skincare routine video', creative_url: '', caption_en: '', caption_hr: '', hashtags: '', status: 'Draft', notes: '', updated_at: '2024-04-09' },
  { id: 'cnt-003', account_id: 'acc-001', week: '2', day: 'Tuesday', platform: 'Meta Ads', entry_type: 'Post', content_pillar: 'Product Promotion', visual_direction: 'Spring collection banner', creative_url: '', caption_en: 'Spring is here — shop the new collection.', caption_hr: '', hashtags: '', status: 'Published', notes: 'CTR 3.2%, ROAS 4.1x', updated_at: '2024-04-02' },
  { id: 'cnt-004', account_id: 'acc-002', week: '1', day: 'Thursday', platform: 'TikTok', entry_type: 'Reel', content_pillar: 'Atmosphere', visual_direction: 'Morning rush behind the scenes', creative_url: '', caption_en: 'Coffee culture starts here. ☕', caption_hr: 'Kava kultura počinje ovdje. ☕', hashtags: '#voltacoffee #dublin #coffee', status: 'Published', notes: '28k views', updated_at: '2024-04-06' },
  { id: 'cnt-005', account_id: 'acc-002', week: '2', day: 'Monday', platform: 'Instagram', entry_type: 'Post', content_pillar: 'Product Promotion', visual_direction: 'New summer menu hero shot', creative_url: '', caption_en: 'Our summer menu just dropped. Come try it.', caption_hr: 'Ljetni meni je stigao. Dođi probati.', hashtags: '#voltacoffee #summermenu', status: 'Draft', notes: 'Waiting on menu confirmation from client', updated_at: '2024-04-11' },
  { id: 'cnt-006', account_id: 'acc-003', week: '1', day: 'Wednesday', platform: 'YouTube', entry_type: 'Post', content_pillar: 'Lifestyle', visual_direction: 'Living room full tour walkthrough', creative_url: '', caption_en: 'Full living room refresh — watch how I did it.', caption_hr: '', hashtags: '#interiordesign #homedecor', status: 'In Review', notes: 'Script approved, editing in progress', updated_at: '2024-04-10' },
  { id: 'cnt-007', account_id: 'acc-004', week: '2', day: 'Friday', platform: 'Meta Ads', entry_type: 'Post', content_pillar: 'Traffic-Driving', visual_direction: 'Summer shred programme promo graphic', creative_url: '', caption_en: 'Summer is coming. Are you ready? Join our 8-week shred.', caption_hr: '', hashtags: '', status: 'Draft', notes: '', updated_at: '2024-04-08' },
  { id: 'cnt-008', account_id: 'acc-005', week: '1', day: 'Monday', platform: 'Instagram', entry_type: 'Post', content_pillar: 'Community', visual_direction: 'Marathon training run shot', creative_url: '', caption_en: 'Week 12 done. Every kilometre counts. 🏃', caption_hr: '', hashtags: '#running #marathon #asics', status: 'Published', notes: '', updated_at: '2024-04-08' },
]

export const mockPayments = [
  { id: 'pay-001', account_id: 'acc-001', amount: '2400', currency: 'EUR', invoice_date: '2024-04-01', due_date: '2024-04-15', paid: false, paid_date: '', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Kiran', notes: 'April retainer' },
  { id: 'pay-002', account_id: 'acc-001', amount: '2400', currency: 'EUR', invoice_date: '2024-03-01', due_date: '2024-03-15', paid: true, paid_date: '2024-03-12', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Kiran', notes: 'March retainer' },
  { id: 'pay-003', account_id: 'acc-002', amount: '1800', currency: 'EUR', invoice_date: '2024-04-01', due_date: '2024-04-10', paid: false, paid_date: '', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Rebeka', notes: 'April retainer' },
  { id: 'pay-004', account_id: 'acc-002', amount: '1800', currency: 'EUR', invoice_date: '2024-03-01', due_date: '2024-03-10', paid: true, paid_date: '2024-03-09', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Rebeka', notes: 'March retainer' },
  { id: 'pay-005', account_id: 'acc-003', amount: '1200', currency: 'EUR', invoice_date: '2024-04-01', due_date: '2024-04-20', paid: false, paid_date: '', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Kiran', notes: '' },
  { id: 'pay-006', account_id: 'acc-004', amount: '2200', currency: 'EUR', invoice_date: '2024-03-15', due_date: '2024-04-01', paid: false, paid_date: '', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Rebeka', notes: 'Overdue — chased 10 Apr' },
  { id: 'pay-007', account_id: 'acc-004', amount: '500', currency: 'EUR', invoice_date: '2024-03-01', due_date: '2024-03-20', paid: true, paid_date: '2024-03-18', recurring: false, recurrence_period: 'One-time', assigned_to: 'Rebeka', notes: 'Ad creative setup fee' },
  { id: 'pay-008', account_id: 'acc-005', amount: '950', currency: 'EUR', invoice_date: '2024-04-01', due_date: '2024-04-18', paid: false, paid_date: '', recurring: true, recurrence_period: 'Monthly', assigned_to: 'Rebeka', notes: '' },
]
